stages:
  - verify
  - test
  - build

include:
  - component: gitlab.dcas.dev/autodevops/components/semgrep@main
  - component: gitlab.dcas.dev/autodevops/components/go-test@main
  - component: gitlab.dcas.dev/autodevops/components/go-build@main
    inputs:
      importPath: cmd/rbac
