apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: go-rbac-proxy
build:
  artifacts:
    - image: dev.local/go-rbac-proxy
      buildpacks:
        builder: harbor.dcas.dev/docker.io/paketobuildpacks/builder:tiny
        runImage: harbor.dcas.dev/docker.io/paketobuildpacks/run:tiny-cnb
        trustBuilder: true
        dependencies:
          paths:
            - cmd/rbac/
            - internal/
            - pkg/
  local:
    push: false
