apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: go-rbac-proxy
build:
  artifacts:
    - image: dev.local/go-rbac-proxy
      ko:
        main: cmd/rbac/
        dependencies:
          paths:
            - cmd/rbac/
            - internal/
            - pkg/
  local:
    push: false
